# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'UCF CogSci'
description: ''
permalink: pretty
logo: "https://static.vecteezy.com/system/resources/thumbnails/000/585/305/small/006-13.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Announcements
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Announcements
    output: true
    description: "General body meetings are every other _____ from ___ to ___"
    feature_text: |
      UCF Cognitive Science
    feature_image: "https://static.vecteezy.com/system/resources/thumbnails/000/585/305/small/006-13.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
