# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://ucf-csc.netlify.app/'
baseurl: ''
title: 'UCF CogSci'
description: ''
permalink: pretty
logo: "https://raw.githubusercontent.com/csc-ucf/alembic-kit/master/assets/logos/CSLogo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /about/
- title: Announcements
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
- title: Discord
  url: "https://discord.gg/paeeVzWbVc"
- title: Instagram
  url: "https://www.instagram.com/ucfcogsci/"
- title: Twitter
  url: "https://twitter.com/ucfcogsci"

# Collections
collections:
  posts:
    title: Announcements
    output: true
    description: "General body meetings are every other ___from ___ to ___"
    feature_text: |
      Announcements
    feature_image: ""

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
